--------------------------------------------------------
--  File created - Monday-April-04-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUCURSALES
--------------------------------------------------------

  CREATE TABLE "CFCUSER"."SUCURSALES" 
   (	"CODIGO_AGENCIA" NUMBER, 
	"NOM_AGENCIA" VARCHAR2(50 BYTE), 
	"MONTO_ASEGURADO" NUMBER, 
	"MONTO_AUTORIZADO" NUMBER, 
	"HORA_APERTURA" TIMESTAMP (6), 
	"HORA_CIERRE" TIMESTAMP (6), 
	"ID_SUCURSAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALDOS
--------------------------------------------------------

  CREATE TABLE "CFCUSER"."SALDOS" 
   (	"CODIGO_USUARIO" VARCHAR2(20 BYTE), 
	"NOM_USUARIO" VARCHAR2(50 BYTE), 
	"CODIGO_AGENCIA" NUMBER, 
	"NOM_AGENCIA" VARCHAR2(20 BYTE), 
	"CODIGO_MONEDA" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ID_SALDO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "CFCUSER"."MOVIMIENTOS" 
   (	"CODIGO_EMPRESA" NUMBER, 
	"FECHA_VALIDA" TIMESTAMP (6), 
	"CODIGO_REGION" VARCHAR2(20 BYTE), 
	"NOM_REGION" VARCHAR2(50 BYTE), 
	"CODIGO_AGENCIA" NUMBER, 
	"NOM_AGENCIA" VARCHAR2(50 BYTE), 
	"CODIGO_USUARIO" NUMBER, 
	"NOM_USUARIO" VARCHAR2(50 BYTE), 
	"HORA_MOVIMIENTO" TIMESTAMP (6), 
	"CODIGO_TIPO_TRANSACCION" NUMBER, 
	"CODIGO_MONEDA" NUMBER, 
	"ENTRADA_SALIDA" VARCHAR2(20 BYTE), 
	"CLIENTE_EMPRESA" VARCHAR2(20 BYTE), 
	"DESC_TRANSACCION" VARCHAR2(50 BYTE), 
	"MONTO_VALOR" NUMBER, 
	"ID_MOVIMIENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORICOS
--------------------------------------------------------

  CREATE TABLE "CFCUSER"."HISTORICOS" 
   (	"CODIGO_EMPRESA" NUMBER, 
	"FECHA_VALIDA" TIMESTAMP (6), 
	"CODIGO_REGION" VARCHAR2(20 BYTE), 
	"NOM_REGION" VARCHAR2(50 BYTE), 
	"CODIGO_AGENCIA" NUMBER, 
	"NOM_AGENCIA" VARCHAR2(50 BYTE), 
	"CODIGO_USUARIO" NUMBER, 
	"NOM_USUARIO" VARCHAR2(50 BYTE), 
	"HORA_MOVIMIENTO" TIMESTAMP (6), 
	"CODIGO_TIPO_TRANSACCION" NUMBER, 
	"CODIGO_MONEDA" NUMBER, 
	"ENTRADA_SALIDA" VARCHAR2(20 BYTE), 
	"CLIENTE_EMPRESA" VARCHAR2(20 BYTE), 
	"DESC_TRANSACCION" VARCHAR2(50 BYTE), 
	"MONTO_VALOR" NUMBER, 
	"ID_HISTORICO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CFCUSER.SUCURSALES
SET DEFINE OFF;
Insert into CFCUSER.SUCURSALES (CODIGO_AGENCIA,NOM_AGENCIA,MONTO_ASEGURADO,MONTO_AUTORIZADO,HORA_APERTURA,HORA_CIERRE,ID_SUCURSAL) values (12,'GUAPILES',null,null,null,null,12);
Insert into CFCUSER.SUCURSALES (CODIGO_AGENCIA,NOM_AGENCIA,MONTO_ASEGURADO,MONTO_AUTORIZADO,HORA_APERTURA,HORA_CIERRE,ID_SUCURSAL) values (11,'LIMON',null,null,null,null,11);
REM INSERTING into CFCUSER.SALDOS
SET DEFINE OFF;
Insert into CFCUSER.SALDOS (CODIGO_USUARIO,NOM_USUARIO,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_MONEDA,FECHA,ID_SALDO) values ('1','Juan C',2,'Puntarenas',null,null,200);
Insert into CFCUSER.SALDOS (CODIGO_USUARIO,NOM_USUARIO,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_MONEDA,FECHA,ID_SALDO) values ('2','Maria',1,'Central',null,null,3300);
REM INSERTING into CFCUSER.MOVIMIENTOS
SET DEFINE OFF;
Insert into CFCUSER.MOVIMIENTOS (CODIGO_EMPRESA,FECHA_VALIDA,CODIGO_REGION,NOM_REGION,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_USUARIO,NOM_USUARIO,HORA_MOVIMIENTO,CODIGO_TIPO_TRANSACCION,CODIGO_MONEDA,ENTRADA_SALIDA,CLIENTE_EMPRESA,DESC_TRANSACCION,MONTO_VALOR,ID_MOVIMIENTO) values (1,null,'001','SARAPIQUI',null,null,null,null,null,null,1,null,null,null,null,22);
Insert into CFCUSER.MOVIMIENTOS (CODIGO_EMPRESA,FECHA_VALIDA,CODIGO_REGION,NOM_REGION,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_USUARIO,NOM_USUARIO,HORA_MOVIMIENTO,CODIGO_TIPO_TRANSACCION,CODIGO_MONEDA,ENTRADA_SALIDA,CLIENTE_EMPRESA,DESC_TRANSACCION,MONTO_VALOR,ID_MOVIMIENTO) values (2,null,null,'pz',null,null,null,null,null,null,2,null,null,null,null,33);
Insert into CFCUSER.MOVIMIENTOS (CODIGO_EMPRESA,FECHA_VALIDA,CODIGO_REGION,NOM_REGION,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_USUARIO,NOM_USUARIO,HORA_MOVIMIENTO,CODIGO_TIPO_TRANSACCION,CODIGO_MONEDA,ENTRADA_SALIDA,CLIENTE_EMPRESA,DESC_TRANSACCION,MONTO_VALOR,ID_MOVIMIENTO) values (3,null,null,'hojancha',null,null,null,null,null,null,1,null,null,null,null,44);
REM INSERTING into CFCUSER.HISTORICOS
SET DEFINE OFF;
Insert into CFCUSER.HISTORICOS (CODIGO_EMPRESA,FECHA_VALIDA,CODIGO_REGION,NOM_REGION,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_USUARIO,NOM_USUARIO,HORA_MOVIMIENTO,CODIGO_TIPO_TRANSACCION,CODIGO_MONEDA,ENTRADA_SALIDA,CLIENTE_EMPRESA,DESC_TRANSACCION,MONTO_VALOR,ID_HISTORICO) values (1,to_timestamp('16-MAR-16 02.28.29.501000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,'chorotega',101,'chorotegas',2,'Carlos ',to_timestamp('15-MAR-16 02.29.13.643000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,'E','C','EFECTIVO SALIDA
',545322.2,2);
Insert into CFCUSER.HISTORICOS (CODIGO_EMPRESA,FECHA_VALIDA,CODIGO_REGION,NOM_REGION,CODIGO_AGENCIA,NOM_AGENCIA,CODIGO_USUARIO,NOM_USUARIO,HORA_MOVIMIENTO,CODIGO_TIPO_TRANSACCION,CODIGO_MONEDA,ENTRADA_SALIDA,CLIENTE_EMPRESA,DESC_TRANSACCION,MONTO_VALOR,ID_HISTORICO) values (1,to_timestamp('16-MAR-16 02.20.21.515000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'100','Brunca',1,'BRUNCAS',1,'Juan C',to_timestamp('16-MAR-16 02.20.28.970000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,1,'E','C','DEPOSITO EN EFECTIVO',20000,1);
--------------------------------------------------------
--  DDL for Index SUCURSALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CFCUSER"."SUCURSALES_PK" ON "CFCUSER"."SUCURSALES" ("ID_SUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALDOS_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CFCUSER"."SALDOS_INDEX1" ON "CFCUSER"."SALDOS" ("ID_SALDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOVIMIENTOS_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CFCUSER"."MOVIMIENTOS_INDEX1" ON "CFCUSER"."MOVIMIENTOS" ("ID_MOVIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORICOS_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CFCUSER"."HISTORICOS_INDEX1" ON "CFCUSER"."HISTORICOS" ("ID_HISTORICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUCURSALES
--------------------------------------------------------

  ALTER TABLE "CFCUSER"."SUCURSALES" ADD CONSTRAINT "SUCURSALES_PK" PRIMARY KEY ("ID_SUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CFCUSER"."SUCURSALES" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALDOS
--------------------------------------------------------

  ALTER TABLE "CFCUSER"."SALDOS" ADD CONSTRAINT "SALDOS_PK" PRIMARY KEY ("ID_SALDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CFCUSER"."SALDOS" MODIFY ("ID_SALDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "CFCUSER"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTOS_PK" PRIMARY KEY ("ID_MOVIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CFCUSER"."MOVIMIENTOS" MODIFY ("ID_MOVIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORICOS
--------------------------------------------------------

  ALTER TABLE "CFCUSER"."HISTORICOS" ADD CONSTRAINT "HISTORICOS_PK" PRIMARY KEY ("ID_HISTORICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CFCUSER"."HISTORICOS" MODIFY ("ID_HISTORICO" NOT NULL ENABLE);
